### ISSUE TITLE
Реализовать проверку ссылочной целостности для объектов метаданных конфигурации

### ISSUE THREAD

**Issue by tretyakevich** [1C-Company/dt-project-checks#18]
### Описание проблемы

В настоящий момент существует ряд ошибок, связанных с нарушением ссылочной целостности в объектах метаданных конфигурации. Данные ошибки приводят либо к невозможности публикации в ИБ (с совершенно недостаточным уровнем информации для локации и последующего исправления проблемы), либо к ошибкам в рантайме.

### Описание решения проблемы

Предлагаю реализовать проверку ссылочной целостности объектов метаданных, с возможностью блокировки публикации в ИБ при обнаружении соответствующих проблем (и до их исправления).
Это позволит:

1. Предоставлять адресную информацию о проблемах ссылочной целостности
2. В последующем реализовать механизм быстрого исправления данных проблем

**Comment by marmyshev** [comment]
А не дубль ли это #3
