### ISSUE TITLE
Реализовать проверку на наличие дубликатов среди идентификаторов элементов форм

### ISSUE THREAD

**Issue by AlmazNasibullin** [1C-Company/dt-project-checks#7]
### Описание проблемы

При одновременной доработке одной формы двумя и более разработчиками может возникнуть ситуация, что появляются дубликаты среди идентификаторов элементов форм, для этого достаточно добавить каждому из разработчиков новый элемент формы. Наличие дубликатов среди идентификаторов элементов форм "ломает" форму в рантайме.

### Описание решения проблемы

Предлагается реализовать проверку с возможность исправления для вышеописанной проблемы наличия дубликатов среди идентификаторов элементов форм.

**Comment by marmyshev** [comment]
Бывают ситуации когда идентификатора у элемента нет - это тоже ошибка. Нужно фиксить так же - генерить новый идентификатор
